In [1]:
# Numpy
# Creating Array
import numpy as np
 
arr1 = np.array([10,15,16,17,18])
print(arr1)

[10 15 16 17 18]


In [2]:
arr2 = np.array([[43, 56,54],
                [32,31,22],
                [66,68,88]])
 
print(arr2)

[[43 56 54]
 [32 31 22]
 [66 68 88]]


In [3]:
zeros = np.ones((3,4))
print(zeros)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
# Line space
# start , end, 5
linsp = np.linspace(0, 1, 7)
print(linsp)

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [5]:
rnge = np.arange(0,10,2.5)
print(rnge)

[0.  2.5 5.  7.5]
